### ISSUE TITLE
Rmd hunks

### ISSUE THREAD

**Issue by maelle** [gadenbuie/garrickadenbuie-com#55]
Thanks again for your post about re-usable Rmd pieces @gadenbuie! 

I'd have left a comment if I could, so [yes you're missing out](https://twitter.com/grrrck/status/1179379856196489216) (just kidding).

Compared to your post, I now put re-usable Rmd pieces under man/rmdhunks/ see for instance https://github.com/lockedata/hubspot that passes R CMD check and whose pkgdown website looks fine.

Downsides to keeping pieces under vignettes/ : pieces not available during R CMD check, and pkgdown builds them as unnamed articles.

See also https://github.com/r-hub/blog/pull/44

**Comment by gadenbuie** [comment]
Thanks @maelle, I appreciate the nudge and reminder!

While I have you -- I've been wondering about the *hunks* word. I used it because that's what Brodie called them [in his package](https://github.com/brodieG/vetr/tree/master/vignettes/rmdhunks), but I'm on the fence about whether that's the most appropriate term. What do you think? At some point I changed the post to say *chunks* in most (but I guess not all) places.

The [Definitive Guide to R Markdown](https://bookdown.org/yihui/rmarkdown/r-code.html) calls them _child_ documents, but they're read into a _chunk_ in the parent document. So in a way they're external _chunks_ that happen to live in separate files.

I guess I'm leaning toward consistently calling them _chunks_ in my post, but I wanted to see what you think first.

**Comment by maelle** [comment]
Ah good question, I used hunks as a folder name but only call them re-usable Rmd pieces (so I like child documents too although calling documents makes them sound self-contained IMO which they are not). I find chunk potentially confusing because I only use it for _code_ chunks. 🤔

**Comment by gadenbuie** [comment]
How about *child chunks*?

**Comment by maelle** [comment]
I am partly in favor of it and partly afraid it is confusing because of code chunks.

**Comment by gadenbuie** [comment]
I agree, and you have a good point. I was hoping consistently putting the two together would be a middle ground... I'll have to think about it a bit. Part of my concern is that _hunks_ sounds too close to a mistake. So Rmd pieces? Or Rmd fragments?

**Comment by maelle** [comment]
I like Rmd fragments!
